# Copyright 2017 Intermodalics
# Original author: Kevin De Martelaere <kevin.demartelaere@intermodalics.eu>

import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)

    bld.recurse('slaveinfo')
